import { exercises, muscleGroups } from '@/data/exercises';
import Link from 'next/link';
import {
  Dumbbell,
  Sparkles,
  Library,
  BarChart3,
  Activity,
  Target,
  ChevronDown,
  Check,
  ArrowRight,
} from 'lucide-react';

export const revalidate = 3600;

export const metadata = {
  title: 'MuscleAtlas — Free Exercise Library, AI Workouts & Diet Planner',
  description:
    'Train smarter with 100+ exercises, AI-powered workout plans, diet planner, progress tracking, and analytics. Your complete fitness companion.',
  openGraph: {
    title: 'MuscleAtlas — Free Exercise Library, AI Workouts & Diet Planner',
    description:
      'Train smarter with 100+ exercises, AI-powered workout plans, diet planner, progress tracking, and analytics. Your complete fitness companion.',
    image: '/og-image.png',
    siteName: 'MuscleAtlas',
    locale: 'en_NG',
    type: 'website',
  },
  alternates: {
    canonical: '/',
  },
}

const features = [
  {
    icon: Library,
    title: 'Exercise Library',
    desc: 'Browse 100+ exercises with video demos, muscle targeting, and detailed instructions.',
  },
  {
    icon: Sparkles,
    title: 'AI Workout Generator',
    desc: 'Get personalized workout plans generated by AI based on your goals and target muscles.',
  },
  {
    icon: BarChart3,
    title: 'Progress Tracking',
    desc: 'Log workouts, track volume, monitor PRs, and watch your strength grow over time.',
  },
  {
    icon: Activity,
    title: 'Analytics Dashboard',
    desc: 'Visualize your training volume, streaks, muscle balance, and personal records.',
  },
  {
    icon: Target,
    title: 'Smart Templates',
    desc: 'Start with proven workout splits and customize them to fit your schedule.',
  },
  {
    icon: Check,
    title: 'Completely Free',
    desc: 'No subscriptions, no hidden fees. All features are free forever.',
  },
];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b sticky top-0 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 z-50">
        <nav className="container max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-foreground text-background">
              <Dumbbell className="w-5 h-5" />
            </div>
            <span className="text-lg font-bold">MuscleAtlas</span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm">
            <a
              href="#features"
              className="text-muted-foreground hover:text-foreground transition-colors"
            >
              Features
            </a>
            <a
              href="#stats"
              className="text-muted-foreground hover:text-foreground transition-colors"
            >
              Stats
            </a>
            <Link
              href="/app"
              className="text-muted-foreground hover:text-foreground transition-colors"
            >
              App
            </Link>
            <Link
              href="/about"
              className="text-muted-foreground hover:text-foreground transition-colors"
            >
              About
            </Link>
          </div>
          <div className="flex items-center gap-2">
            <Link
              href="/app"
              className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-9 px-3"
            >
              Sign In
            </Link>
            <Link
              href="/app"
              className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-3 hidden sm:inline-flex"
            >
              Get Started
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero */}
      <section className="relative flex-1 flex items-center justify-center min-h-[80vh] overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-background via-background to-muted/30" />
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:40px_40px]" />
        <div className="relative z-10 container max-w-6xl mx-auto px-4 text-center py-20">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4 text-primary" /> Your Fitness Journey
            Starts Here
          </div>
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6">
            Free Exercise Library &<br />
            <span className="text-primary">AI Workout Generator</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-8">
            Build muscle, track progress, and achieve your fitness goals with
            personalized AI workouts — all completely free.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Link
              href="/app"
              className="inline-flex items-center justify-center rounded-md text-base font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-11 px-8"
            >
              <Dumbbell className="w-5 h-5 mr-2" /> Start Free
            </Link>
            <Link
              href="/app"
              className="inline-flex items-center justify-center rounded-md text-base font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-11 px-8"
            >
              <Sparkles className="w-5 h-5 mr-2" /> Try the App
            </Link>
          </div>
          <div
            id="stats"
            className="grid grid-cols-3 gap-8 max-w-lg mx-auto"
          >
            <div className="text-center">
              <div className="text-3xl font-bold">{exercises.length}+</div>
              <div className="text-sm text-muted-foreground">Exercises</div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold">{muscleGroups.length}</div>
              <div className="text-sm text-muted-foreground">
                Muscle Groups
              </div>
            </div>
            <div className="text-center">
              <div className="text-3xl font-bold">1</div>
              <div className="text-sm text-muted-foreground">AI Generator</div>
            </div>
          </div>
        </div>
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce">
          <ChevronDown className="w-6 h-6 text-muted-foreground" />
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 bg-muted/20">
        <div className="container max-w-6xl mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-3">Everything You Need</h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              A complete fitness toolkit designed to help you build muscle and
              track your progress.
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div
                key={i}
                className="rounded-lg border bg-card text-card-foreground shadow-sm border-0 bg-background shadow-sm hover:shadow-md transition-shadow"
              >
                <div className="p-6 pt-6">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                    <f.icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-semibold mb-2">{f.title}</h3>
                  <p className="text-sm text-muted-foreground">{f.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20">
        <div className="container max-w-4xl mx-auto px-4 text-center">
          <div className="rounded-lg border bg-card text-card-foreground shadow-sm border-primary/20 bg-gradient-to-br from-primary/5 to-background">
            <div className="p-12 px-8">
              <h2 className="text-3xl font-bold mb-3">
                Ready to Transform?
              </h2>
              <p className="text-muted-foreground mb-6 max-w-md mx-auto">
                Join thousands of athletes using MuscleAtlas to build strength
                and track their fitness journey.
              </p>
              <div className="flex flex-col sm:flex-row gap-3 justify-center">
                <Link
                  href="/app"
                  className="inline-flex items-center justify-center rounded-md text-base font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-11 px-8"
                >
                  Create Free Account{' '}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Link>
                <Link
                  href="/app"
                  className="inline-flex items-center justify-center rounded-md text-base font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-11 px-8"
                >
                  Browse Exercises
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t bg-muted/30">
        <div className="container max-w-6xl mx-auto px-4 py-8">
          <div className="grid sm:grid-cols-3 gap-8 text-sm">
            <div>
              <div className="flex items-center gap-2 font-bold mb-3">
                <Dumbbell className="w-4 h-4" /> MuscleAtlas
              </div>
              <p className="text-muted-foreground">
                Free exercise library, AI workout generator, and progress
                tracker.
              </p>
            </div>
            <div>
              <h4 className="font-medium mb-3">Links</h4>
              <div className="space-y-2">
                <Link
                  href="/app"
                  className="block text-muted-foreground hover:text-foreground"
                >
                  App
                </Link>
                <Link
                  href="/about"
                  className="block text-muted-foreground hover:text-foreground"
                >
                  About
                </Link>
                <Link
                  href="/privacy"
                  className="block text-muted-foreground hover:text-foreground"
                >
                  Privacy
                </Link>
                <Link
                  href="/terms"
                  className="block text-muted-foreground hover:text-foreground"
                >
                  Terms
                </Link>
              </div>
            </div>
            <div>
              <h4 className="font-medium mb-3">Contact</h4>
              <p className="text-muted-foreground">
                support@muscleatlas.site
              </p>
            </div>
          </div>
          <div className="border-t mt-8 pt-4 text-center text-xs text-muted-foreground">
            &copy; {new Date().getFullYear()} MuscleAtlas. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
